version: "3.9"
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi-ece-2025
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
      SINGLE_USER_CREDENTIALS_USERNAME: CHARLO
      SINGLE_USER_CREDENTIALS_PASSWORD: AZERTYUIOPQS
    volumes:
    - /Users/charlesdeblauwe/Projet-Voile/gpx_input:/data/gpx_input
    - /Users/charlesdeblauwe/Projet-Voile/gpx_output:/data/gpx_output
